# golangci-lint configuration
run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - tmp
    - bin
  skip-files:
    - ".*_test.go"

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  enable:
    - asciicheck
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - exhaustive
    - exportloopref
    - forcetypeassert
    - gci
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - golint
    - gomnd
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nlreturn
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - structcheck
    - stylecheck
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - wastedassign
    - whitespace
    - wsl

linters-settings:
  gci:
    local-prefixes: adc-sso-service
  
  gocognit:
    min-complexity: 15
  
  gocyclo:
    min-complexity: 15
  
  golint:
    min-confidence: 0.8
  
  gomnd:
    settings:
      mnd:
        checks: argument,case,condition,operation,return,assign
  
  govet:
    check-shadowing: true
  
  lll:
    line-length: 120
  
  misspell:
    locale: US
  
  nestif:
    min-complexity: 4
  
  prealloc:
    simple: true
    range-loops: true
    for-loops: false

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - gomnd
    
    # Exclude known linter issues
    - path: internal/models/
      linters:
        - lll
    
    # Exclude shadow checking on err variables
    - text: "shadow: declaration of \"err\""
      linters:
        - govet
    
    # Exclude certain gosec rules
    - linters:
        - gosec
      text: "G404:"  # Use of weak random number generator

  max-issues-per-linter: 0
  max-same-issues: 0